version: '3.8'
services:
  influxdb:
    image: influxdb:1.8.10
    ports:
      - 8086:8086
    environment:
      - INFLUXDB_DB=k6

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ORG_ROLE=Admin