version: '3.8'
services:
  influxdb:
    image: influxdb:1.8.10
    ports:
      - 8086:8086
    environment:
      - INFLUXDB_DB=k6
      - INFLUXDB_HTTP_MAX_BODY_SIZE=0
    volumes:
      - ./data/influxdb:/var/lib/influxdb

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ORG_ROLE=Admin
    volumes:
      - ./data/grafana:/var/lib/grafana
    
  k6:
    image: grafana/k6
    environment:
      - K6_OUT=influxdb=http://influxdb:8086/k6
    volumes:
      - ./scripts:/scripts

  mariadb:
    image: mariadb
    ports:
      - 3306:3306
    environment:
      - MARIADB_ROOT_PASSWORD=P!ssw0rd
      - MARIADB_DATABASE=arise
    volumes:
      - ./data/mariadb:/var/lib/mysql

  redis:
    image: redis
    ports:
      - 6379:6379